### ISSUE TITLE
Does support swagger 2.0

### ISSUE THREAD

**Issue by AndreLobato** [core-api/python-openapi-codec#22]
I am trying to load a definition file I've created with the Swagger editor, and seems a valid document in the editor, but the codec returns only the GET details endpoints. So I suppose the _parse_document function is just not handling well those definitions as a whole.

**Comment by AndreLobato** [comment]
So the problem in my definitions file was only that I didn't had set `operationId` for the paths. After set rendered the correct document. Maybe is worth to have some comment in the docs.

**Comment by lovelydinosaur** [comment]
Okay, is `operationId` required by the swagger spec or not? That'd determine if we oughta act on this.
