### ISSUE TITLE
Field instantiated with wrong argument list

### ISSUE THREAD

**Issue by danballance** [core-api/python-openapi-codec#29]
I'm getting:

TypeError: __new__() got an unexpected keyword argument 'description'

In decode.py, ~line 56, there is:
```
field = Field(name=name, location=location, required=required, description=field_description)
```

However in this commit in coreapi.document the description field was removed I believe:

https://github.com/core-api/python-client/commit/6dd8ede4857435aed427183cb75bfa9b3d5304f5#diff-bda1bab8e301bc649ee7abf40303bf6d

Am I following the code correctly here? It loos like interfaces have drifted between package versions?

**Comment by lovelydinosaur** [comment]
"It loos like interfaces have drifted between package versions?"

Ack - yup this is my fault. To be resolved shortly. In the meantime install `coreapi 2.1.1`

**Comment by danballance** [comment]
Brilliant, thanks! +1:

**Comment by lovelydinosaur** [comment]
@danballance - Should be resolved in the latest version.
