### ISSUE TITLE
OpenAPICodec extensibility

### ISSUE THREAD

**Issue by itoed** [core-api/python-openapi-codec#33]
Is there a reason why the [`OpenAPICodec`](https://github.com/core-api/python-openapi-codec/blob/1.3.1/openapi_codec/__init__.py#L14) is written as closed for extension?

It would be nice to customize some things like `tags` and `operationId` on the [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object).

The design of the `SchemaGenerator` in DRF and how [you can extend](https://github.com/tomchristie/django-rest-framework/blob/3.6.2/rest_framework/schemas.py#L300-L301)  the `EndpointInspector` seems like a good example for a solution:

```python
class OpenAPIEncoder(object):
    def encode(self, document): pass
    def add_tag_prefix(self, item): pass
    def get_links(self, document): pass
    def get_paths_object(self, document): pass
    def get_operation(self, operation_id, link, tags): pass
    def get_field_description(self, field): pass
    def get_field_type(self, field): pass
    def get_parameters(self, link, encoding): pass
    def get_responses(self, link): pass


class OpenAPICodec(BaseCodec):
    openapi_encoder_cls = OpenAPIEncoder

    def encode(self, document, **options):
        if not isinstance(document, Document):
            raise TypeError('Expected a `coreapi.Document` instance')
        encoder = self.openapi_encoder_cls()
        data = encoder.encode(document)
        return force_bytes(json.dumps(data))
```

Is this something that could be considered?

**Comment by lovelydinosaur** [comment]
Not particularly interested in having to maintain an internal overridable interface for the package,
at least not at the moment.
