### ISSUE TITLE
Handle invalid document in generate_swagger_object

### ISSUE THREAD

**Issue by blueyed** [core-api/python-openapi-codec#8]
django-rest-swagger's `OpenAPIRenderer.get_openapi_specification` might call `OpenAPICodec.dump` with an invalid document (missing url and title).

While this is an error in django-rest-swagger in this case (where I will file an issue for), I think `generate_swagger_object` should be more robust.

`document` is `{'detail': 'Invalid API version. Please provide it in the "Accept" header, e.g. "Accept: application/json; version=1.0".'}`, coming from a 406 response, because of a missing version header.

What do you think?

**Comment by lovelydinosaur** [comment]
`Document` instances are valid with either blank `url` or blank `title`. At least wrt. Core API.

However it's possible that the Open API spec mandates a title and/or url, in which case it would be valid for this particular codec to raise an error in either of these cases. (I think my preference is towards liberal wherever possible, for whatever that's worth)

I didn't understand how the rest of the description tied in with the "coming from a 406 response, because of a missing version header" paragraph?

**Comment by blueyed** [comment]
> I didn't understand how the rest of the description tied in with the "coming from a 406 response, because of a missing version header" paragraph?

That's how I've triggered it: because django-rest-swagger passes in the data from a 406 response (which DRF generates because of a missing "version" header in the request).
It seems like django-rest-swagger 2 does not work with DRF's `AcceptHeaderVersioning` (when a version is required).  Ref: https://github.com/marcgibbons/django-rest-swagger/pull/510 (for django-rest-swagger 0.3).

**Comment by lovelydinosaur** [comment]
If I understand it correctly, then this is actually conflating two separate issues:
1. The Swagger client does not send version headers in it's outgoing requests.
2. The codec should raise an error if it is passed a value that is _not_ a document.

**Comment by blueyed** [comment]
Yes.

And only 2. is relevant here.  I just wanted to explain why/how this might happen.

**Comment by lovelydinosaur** [comment]
Gotcha, thanks!

**Comment by blueyed** [comment]
Should I create a PR for python-openapi-codec?
I've started with some `try…except` hacks already.

**Comment by lovelydinosaur** [comment]
You're welcome to - not sure I get `try...except` hacks - I'd have expected a `assert isinstance(...)` at the start of the `dump()` method or something like that, but perhaps I'm still misunderstanding.

**Comment by marcgibbons** [comment]
@blueyed @tomchristie An assert is instance is definitely needed either in the `dump()` here and/or on the Django REST Swagger OpenAPI's`render()` method. Leaning towards doing it in both places?

**Comment by lovelydinosaur** [comment]
> Leaning towards doing it in both places?

Don't see why not, yup.

**Comment by lovelydinosaur** [comment]
Resolved in #10.
